### ISSUE TITLE
Is there a way for hot reload on dev mode?

### ISSUE THREAD

**Issue by mrkaspa** [swlkr/coast#12]

**Comment by swlkr** [comment]
It should be using ring.middleware.reload to do a reload on every request, let me check it out

**Comment by swlkr** [comment]
Yeah, I tried changing the default "/" route from `"You're coasting on clojure"` to `[:h1 "You're coasting on clojure"]` and I refreshed it and it seems to work...

**Comment by swlkr** [comment]
I just realized this says hot reload… as in no refresh and changes just show up, unfortunately no there is no hot reload 😭
