### ISSUE TITLE
Can't connect to database with user and password

### ISSUE THREAD

**Issue by BlankRain** [swlkr/coast#2]
I have a dev database access with user and password.
when run `lein db/create`
it throw errors:
```
SEVERE: Connection error:
org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided.
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:487)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
        at org.postgresql.Driver.makeConnection(Driver.java:450)
        at org.postgresql.Driver.connect(Driver.java:252)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:359)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:226)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:294)
```

see code at:
https://github.com/swlkr/coast/blob/master/src/coast/db.clj#L9
  {:connection (sql/get-connection (environ/env :database-url))})

**Comment by swlkr** [comment]
Dang it, I assumed a dev database with no username and password. This is definitely broken. Give me a little while and we'll have it fixed, or if you have a fix, I'll gladly pull it in!

**Comment by swlkr** [comment]
Oh you know what, my current user has createdb privileges, and I'm already logged in

```[postgres] # \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 swlkr     | Superuser, Create role, Create DB                          | {}
```

I hardcoded a string here: https://github.com/swlkr/coast/blob/master/src/coast/db.clj#L35 assuming the currently logged in user would have createdb privileges

Oh! I also have trust auth in my `pg_hba.conf`

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust
```

**Comment by swlkr** [comment]
So I'm thinking if you don't want to set trust auth for your postgres server, then I can just add another ENV variable like `:admin-database-url` or ADMIN_DATABASE_URL on the command line and you can set the connection string with the username/password you want to use and coast will use that instead

**Comment by BlankRain** [comment]
http://clojure.github.io/java.jdbc/#clojure.java.jdbc/get-connection 
I check the document.
it support  map and uri and string types as args.
so I just need to add my db-spec in the profiles.clj .
for example:
`
{:dev  {:env {:database-url  {:classname "com.mysql.jdbc.Driver" ; must be in classpath
                                            :subprotocol "mysql"
                                            :dbname "demodb"
                                            :subname "//somehost:3306/somedatabase?characterEncoding=UTF-8"
                                            :user "someuser"
                                            :password "password-of-someuser"}
              :secret "CzRiB3pHAHMTbNPj"
              :port "1337"
              :coast-env "dev"}}
`
It can solve problems.
However, I think the keyword :database-url  is not suitable here.
How about change it to :db-spec-or-uri ?
