### ISSUE TITLE
Tags not rendered in view/posts.clj

### ISSUE THREAD

**Issue by jellea** [swlkr/coast#4]
Hey Sean! Great project, I believe this is exactly what the clojure eco system needs! 

I have a small problem kick starting the demo. After running `lein view/gen posts` (or `lein mvc/gen posts`) the `src/blog/views/posts.clj` contains unrendered mustache tags (for example `{% for col in columns %}`) causing errors on start.

I'd love to contribute, shall I pick this up myself?

**Comment by swlkr** [comment]
Ah dang it, I knew I forgot something. Yeah I switched from mustache in haste to try to cut down on dependencies, must have forgotten to deal with the columns there. My solution was to just build the column string in code and then have the template be legitimately logic-less, just string substitution.

Yeah go ahead and do it if you want to look through some... not so great code haha, I'll await your PR!

**Comment by swlkr** [comment]
This was fixed in https://github.com/swlkr/coast/tree/0.6.9
